name: Generate Documentation

on:
  push:
    branches:
      - main

jobs:
  generate-docc:
    strategy:
      matrix:
        os: [ubuntu-latest]
        swift: ["6.1"]
        build_mode: ["debug"]
    name: Generate Documentation
    runs-on: ${{ matrix.os }}
    steps:
      - uses: swift-actions/setup-swift@v2
        with:
          swift-version: ${{ matrix.swift }}

      - name: Print OS and Swift version
        run: |
          uname -a
          swift --version

      - name: Setup SSH Key
        run: |
          rm -rf ~/.ssh
          mkdir -m 0700 ~/.ssh
          echo "${{ secrets.WORKFLOWS_SSH_PRIVATE_KEY }}" > ~/.ssh/id_ed25519
          echo "${{ secrets.WORKFLOWS_SSH_PUBLIC_KEY }}" > ~/.ssh/id_ed25519.pub
          chmod 0600 ~/.ssh/id_ed25519
          eval "$(ssh-agent -s)"
          ssh-add ~/.ssh/id_ed25519

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Generate Documentation
        uses: fwcd/swift-docc-action@v1
        with:
          target: FSM
          output: ./docs
          hosting-base-path: ${{ github.event.repository.name }}
          disable-indexing: 'true'
          transform-for-static-hosting: 'true'

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
          force_orphan: true
